#!/bin/sh

DAEMON="home-persistence-mount"
PIDFILE="/var/run/$DAEMON.pid"

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/opt/$DAEMON.sh"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

case "$1" in
	start)
		"$1";;
	stop|restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
