HELLO_WORLD_VERSION = 0.0.1
HELLO_WORLD_SITE = msf/ems/dhs
HELLO_WORLD_SITE_METHOD = local
HELLO_WORLD_INSTALL_STAGING = NO
HELLO_LICENSE = GPL-2.0+
HELLO_LICENSE_FILES = COPYING

LIBCEC_INSTALL_STAGING = YES
LIBCEC_DEPENDENCIES = host-pkgconf libplatform
# define HELLO_WORLD_BUILD_CMDS
# 	$(MAKE) CC="$(TARGET_CC)" LD="$(TARGET_LD)" -C $(@D) all
# endef

# define HELLO_WORLD_INSTALL_TARGET_CMDS
# 	$(INSTALL) -D -m 0755 $(@D)/Calculator $(TARGET_DIR)/usr/lib
# endef

# $(eval $(generic-package))